from pymongo import MongoClient
from datetime import datetime, timedelta
from bson.objectid import ObjectId

# Connect to local MongoDB instance
client = MongoClient("mongodb://localhost:27017/")
db = client["lmats_db"]

# Collections
users_col = db["Users"]
time_legend_col = db["TimeLegend"]
attendance_col = db["AttendanceLogs"]
leave_col = db["LeaveRequests"]
settings_col = db["GlobalSettings"]

def init_db():
    time_legend_col.delete_one({"code": "WK"})
    time_legend_col.delete_one({"code": "LV"})
    
    codes = [
        {"code": "EF", "description": "Early First Half"}, {"code": "EH", "description": "Early Half"},
        {"code": "ES", "description": "Early Second Half"}, {"code": "CF", "description": "Core First Half"},
        {"code": "CH", "description": "Core Half"}, {"code": "CS", "description": "Core Second Half"},
        {"code": "SF", "description": "Standard First Half"}, {"code": "SH", "description": "Standard Half"},
        {"code": "SS", "description": "Standard Second Half"}, {"code": "WP", "description": "Work Present"},
        {"code": "AF", "description": "Absent First Half"}, {"code": "AH", "description": "Absent Half"},
        {"code": "AS", "description": "Absent Second Half"}
    ]
    for c in codes:
        time_legend_col.update_one({"code": c["code"]}, {"$set": c}, upsert=True)

    if users_col.count_documents({"username": "admin"}) == 0:
        users_col.insert_one({
            "user_id": "A001", "username": "admin", "password": "adminpassword",
            "role": "Admin", "manager_id": None
        })

def authenticate_user(username, password):
    return users_col.find_one({"username": username, "password": password})

def get_time_codes():
    # Exclude invalid codes
    return [doc["code"] for doc in time_legend_col.find({"code": {"$nin": ["WK", "LV"]}}, {"_id": 0, "code": 1})]

def get_users_by_role(role=None):
    query = {"role": role} if role else {}
    return list(users_col.find(query, {"_id": 0}))

def get_team_members(manager_id):
    return list(users_col.find({"manager_id": manager_id}, {"_id": 0}))

def log_attendance(user_id, date, code, place, location, da="", logged_by_id=None, is_locked=False):
    date_str = date.strftime("%Y-%m-%d")
    existing = attendance_col.find_one({"UserID": user_id, "Date": date_str})
    
    # Block modification if record is locked and the modifier is the employee
    if existing and existing.get("is_locked", False) and logged_by_id == user_id:
        return False, "Locked"
        
    attendance_col.update_one(
        {"UserID": user_id, "Date": date_str},
        {"$set": {
            "TimeCode": code, "Place": place, "Location": location, "DA": da,
            "LoggedAt": datetime.now(), "LoggedBy": logged_by_id, "is_locked": is_locked
        }},
        upsert=True
    )
    return True, "Success"

def log_attendance_from_leave(user_id, start_date_str, end_date_str, time_code, manager_id):
    start = datetime.strptime(start_date_str, "%Y-%m-%d")
    end = datetime.strptime(end_date_str, "%Y-%m-%d")
    delta = end - start
    for i in range(delta.days + 1):
        current_date = start + timedelta(days=i)
        # Lock attendance logs generated by managers
        log_attendance(user_id, current_date, time_code, "Leave Approval", "N/A", "", manager_id, is_locked=True)

def get_user_attendance(user_id):
    return list(attendance_col.find({"UserID": user_id}, {"_id": 0}).sort("Date", -1))

def get_attendance_for_date(date_str):
    return list(attendance_col.find({"Date": date_str}, {"_id": 0}))

def apply_leave(user_id, manager_id, start_date, end_date, l_type, reason):
    leave_col.insert_one({
        "UserID": user_id, "ManagerID": manager_id,
        "StartDate": start_date.strftime("%Y-%m-%d"),
        "EndDate": end_date.strftime("%Y-%m-%d"),
        "Type": l_type, "Reason": reason,
        "Status": "Pending", "AppliedAt": datetime.now()
    })

def get_my_leaves(user_id):
    return list(leave_col.find({"UserID": user_id}, {"_id": 0}).sort("StartDate", -1))

def get_pending_team_leaves(manager_id):
    return list(leave_col.find({"ManagerID": manager_id, "Status": "Pending"}))

def get_team_leave_history(manager_id):
    return list(leave_col.find({"ManagerID": manager_id, "Status": {"$in": ["Approved", "Rejected"]}}).sort("AppliedAt", -1))

def update_leave_status_with_remarks(request_id, status, remarks):
    leave_col.update_one({"_id": ObjectId(request_id)}, {"$set": {"Status": status, "ManagerRemarks": remarks}})

def update_password(user_id, new_password):
    users_col.update_one({"user_id": user_id}, {"$set": {"password": new_password}})

def get_all_attendance_logs():
    return list(attendance_col.find({}, {"_id": 0}))